[2024-11-26T14:18:20.770-0600] {processor.py:186} INFO - Started process (PID=17915) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:18:20.770-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:18:20.771-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:18:20.771-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:18:20.781-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:18:20.781-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:18:20.781-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:18:20.781-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:18:20.781-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:18:20.810-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-11-26T14:19:59.052-0600] {processor.py:186} INFO - Started process (PID=18094) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:19:59.052-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:19:59.053-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:19:59.053-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:19:59.063-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:19:59.063-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:19:59.063-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:19:59.063-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:19:59.063-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:19:59.093-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-11-26T14:22:13.690-0600] {processor.py:186} INFO - Started process (PID=18354) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:22:13.691-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:22:13.691-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:22:13.691-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:22:13.701-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:22:13.701-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:22:13.701-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:22:13.701-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:22:13.701-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:22:13.731-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-11-26T14:24:22.468-0600] {processor.py:186} INFO - Started process (PID=18619) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:24:22.470-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:24:22.470-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:24:22.470-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:24:22.480-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:24:22.480-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:24:22.480-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:24:22.480-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:24:22.480-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:24:22.511-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T14:26:30.813-0600] {processor.py:186} INFO - Started process (PID=18868) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:26:30.814-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:26:30.815-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:26:30.815-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:26:30.825-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:26:30.825-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:26:30.825-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:26:30.825-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:26:30.825-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:26:30.856-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T14:28:38.558-0600] {processor.py:186} INFO - Started process (PID=19097) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:28:38.559-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:28:38.559-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:28:38.559-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:28:38.570-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:28:38.570-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:28:38.570-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:28:38.570-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:28:38.570-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:28:38.601-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T14:36:43.233-0600] {processor.py:186} INFO - Started process (PID=19591) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:36:43.234-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:36:43.235-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:36:43.235-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:36:43.245-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:36:43.245-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:36:43.245-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:36:43.245-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:36:43.245-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:36:43.275-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T14:38:23.188-0600] {processor.py:186} INFO - Started process (PID=19762) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:38:23.188-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:38:23.189-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:38:23.189-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:38:23.200-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:38:23.199-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:38:23.200-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:38:23.200-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:38:23.200-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:38:23.231-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-11-26T14:40:40.998-0600] {processor.py:186} INFO - Started process (PID=20029) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:40:40.999-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:40:40.999-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:40:40.999-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:40:41.009-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:40:41.009-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:40:41.010-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:40:41.009-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:40:41.010-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:40:41.040-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T14:42:50.587-0600] {processor.py:186} INFO - Started process (PID=20265) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:42:50.587-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:42:50.587-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:42:50.587-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:42:50.598-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:42:50.598-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:42:50.598-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:42:50.598-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:42:50.598-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:42:50.628-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T14:45:03.991-0600] {processor.py:186} INFO - Started process (PID=20528) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:45:03.992-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:45:03.992-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:45:03.992-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:45:04.003-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:45:04.003-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:45:04.003-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:45:04.003-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:45:04.003-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:45:04.034-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T14:47:12.913-0600] {processor.py:186} INFO - Started process (PID=20778) to work on /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:47:12.913-0600] {processor.py:914} INFO - Processing file /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T14:47:12.913-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:47:12.913-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:47:12.923-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:47:12.923-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T14:47:12.923-0600] {logging_mixin.py:190} INFO - [2024-11-26T14:47:12.923-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T14:47:12.923-0600] {processor.py:927} WARNING - No viable dags retrieved from /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T14:47:12.954-0600] {processor.py:208} INFO - Processing /Users/beprathap/PycharmProjects/YouTube-airflow/airflow-venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:02:00.340-0600] {processor.py:186} INFO - Started process (PID=21410) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:02:00.341-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:02:00.341-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:02:00.341-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:02:00.352-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:02:00.352-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:02:00.352-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:02:00.352-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:02:00.352-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:02:00.382-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T15:03:42.967-0600] {processor.py:186} INFO - Started process (PID=21600) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:03:42.968-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:03:42.968-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:03:42.968-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:03:42.978-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:03:42.978-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:03:42.978-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:03:42.978-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:03:42.978-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:03:43.009-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:06:01.395-0600] {processor.py:186} INFO - Started process (PID=21847) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:06:01.395-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:06:01.396-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:06:01.396-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:06:01.406-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:06:01.406-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:06:01.406-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:06:01.406-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:06:01.406-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:06:01.436-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:08:24.579-0600] {processor.py:186} INFO - Started process (PID=22150) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:08:24.580-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:08:24.581-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:08:24.580-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:08:24.592-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:08:24.592-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:08:24.592-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:08:24.592-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:08:24.593-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:08:24.623-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-11-26T15:16:59.685-0600] {processor.py:186} INFO - Started process (PID=22422) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:16:59.687-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:16:59.687-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:16:59.687-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:16:59.698-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:16:59.698-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:16:59.698-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:16:59.698-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:16:59.698-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:16:59.729-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T15:18:35.829-0600] {processor.py:186} INFO - Started process (PID=22608) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:18:35.829-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:18:35.830-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:18:35.830-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:18:35.840-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:18:35.840-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:18:35.840-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:18:35.840-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:18:35.840-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:18:35.871-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:20:52.679-0600] {processor.py:186} INFO - Started process (PID=22867) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:20:52.680-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:20:52.680-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:20:52.680-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:20:52.690-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:20:52.690-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:20:52.690-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:20:52.690-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:20:52.690-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:20:52.721-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:23:05.364-0600] {processor.py:186} INFO - Started process (PID=23142) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:23:05.364-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:23:05.365-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:23:05.365-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:23:05.375-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:23:05.375-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:23:05.375-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:23:05.375-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:23:05.375-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:23:05.406-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:33:53.120-0600] {processor.py:186} INFO - Started process (PID=23514) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:33:53.121-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:33:53.121-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:33:53.121-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:33:53.132-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:33:53.132-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:33:53.132-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:33:53.132-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:33:53.132-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:33:53.162-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T15:35:32.023-0600] {processor.py:186} INFO - Started process (PID=23705) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:35:32.023-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:35:32.023-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:35:32.023-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:35:32.034-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:35:32.033-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:35:32.034-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:35:32.034-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:35:32.034-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:35:32.064-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-11-26T15:37:47.361-0600] {processor.py:186} INFO - Started process (PID=23965) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:37:47.361-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:37:47.362-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:37:47.362-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:37:47.373-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:37:47.373-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:37:47.373-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:37:47.373-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:37:47.374-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:37:47.404-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T15:40:00.889-0600] {processor.py:186} INFO - Started process (PID=24217) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:40:00.890-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:40:00.890-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:40:00.890-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:40:00.902-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:40:00.901-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:40:00.902-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:40:00.902-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:40:00.902-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:40:00.932-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-11-26T15:42:18.740-0600] {processor.py:186} INFO - Started process (PID=24470) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:42:18.741-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:42:18.741-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:42:18.741-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:42:18.751-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:42:18.751-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:42:18.751-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:42:18.751-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:42:18.752-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:42:18.782-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:44:34.535-0600] {processor.py:186} INFO - Started process (PID=24725) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:44:34.535-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:44:34.535-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:44:34.535-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:44:34.546-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:44:34.546-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:44:34.546-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:44:34.546-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:44:34.546-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:44:34.577-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T15:46:50.463-0600] {processor.py:186} INFO - Started process (PID=24973) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:46:50.464-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:46:50.464-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:46:50.464-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:46:50.475-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:46:50.475-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:46:50.475-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:46:50.475-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:46:50.475-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:46:50.506-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-11-26T15:49:01.987-0600] {processor.py:186} INFO - Started process (PID=25230) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:49:01.987-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:49:01.988-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:49:01.987-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:49:01.999-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:49:01.999-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:49:01.999-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:49:01.999-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:49:01.999-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:49:02.030-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T15:51:12.630-0600] {processor.py:186} INFO - Started process (PID=25496) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:51:12.630-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:51:12.631-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:51:12.631-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:51:12.643-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:51:12.643-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:51:12.643-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:51:12.643-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:51:12.643-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:51:12.674-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-11-26T15:53:30.964-0600] {processor.py:186} INFO - Started process (PID=25743) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:53:30.964-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:53:30.965-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:53:30.965-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:53:30.975-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:53:30.975-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:53:30.976-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:53:30.975-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:53:30.976-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:53:31.006-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T15:55:53.824-0600] {processor.py:186} INFO - Started process (PID=26044) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:55:53.825-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:55:53.826-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:55:53.826-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:55:53.837-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:55:53.837-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:55:53.838-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:55:53.837-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:55:53.838-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:55:53.869-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-11-26T15:58:12.624-0600] {processor.py:186} INFO - Started process (PID=26313) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:58:12.625-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T15:58:12.625-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:58:12.625-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:58:12.635-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:58:12.635-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T15:58:12.636-0600] {logging_mixin.py:190} INFO - [2024-11-26T15:58:12.635-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T15:58:12.636-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T15:58:12.666-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T16:00:28.260-0600] {processor.py:186} INFO - Started process (PID=26597) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:00:28.262-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T16:00:28.262-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:00:28.262-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:00:28.273-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:00:28.273-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T16:00:28.273-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:00:28.273-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T16:00:28.273-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:00:28.303-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-11-26T16:02:42.496-0600] {processor.py:186} INFO - Started process (PID=26853) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:02:42.498-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T16:02:42.498-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:02:42.498-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:02:42.509-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:02:42.509-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T16:02:42.509-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:02:42.509-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T16:02:42.509-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:02:42.540-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-11-26T16:04:58.753-0600] {processor.py:186} INFO - Started process (PID=27104) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:04:58.753-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T16:04:58.753-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:04:58.753-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:04:58.763-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:04:58.763-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T16:04:58.764-0600] {logging_mixin.py:190} INFO - [2024-11-26T16:04:58.764-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T16:04:58.764-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T16:04:58.794-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-11-26T17:17:35.735-0600] {processor.py:186} INFO - Started process (PID=27361) to work on /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T17:17:35.736-0600] {processor.py:914} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-26T17:17:35.736-0600] {logging_mixin.py:190} INFO - [2024-11-26T17:17:35.736-0600] {dagbag.py:588} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T17:17:35.746-0600] {logging_mixin.py:190} INFO - [2024-11-26T17:17:35.746-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-26T17:17:35.746-0600] {logging_mixin.py:190} INFO - [2024-11-26T17:17:35.746-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-26T17:17:35.746-0600] {processor.py:927} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-26T17:17:35.775-0600] {processor.py:208} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
